#!/usr/bin/env bash

sh ~/.config/eww/scripts/get_active_layout

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
	stdbuf -o0 awk -F '>>|,' -e '/^activelayout>>/ {print $3}'
